from __future__ import annotations

import cgi
import html
import io
import json
import re
import threading
import traceback
import webbrowser
from datetime import datetime
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any, Dict, List, Optional, Tuple
from urllib.parse import parse_qs, urlparse
from urllib.error import HTTPError
from urllib.request import Request, urlopen

import numpy as np
import pandas as pd


HOST = "127.0.0.1"
DEFAULT_PORT = 8785

OPENAI_LLM_MODELS = [
    ("gpt-5.4-mini", "GPT-5.4 mini - low cost, strong general reasoning"),
    ("gpt-5-mini", "GPT-5 mini - low cost, strong reasoning"),
    ("gpt-5-nano", "GPT-5 nano - lowest cost, light reasoning"),
    ("o3-mini", "o3-mini - moderate cost, dedicated reasoning"),
    ("o4-mini", "o4-mini - moderate cost, fast o-series reasoning"),
    ("gpt-4.1-mini", "GPT-4.1 mini - low cost, fastest baseline"),
]

BASELINE_COLUMNS = {
    "baseline_predicted_outcome",
    "baseline_positive_probability",
    "baseline_confidence",
    "baseline_correct",
}

ABLATION_VARIANTS: Dict[str, Dict[str, str]] = {
    "full_e2r2": {
        "label": "Full E2R2",
        "description": "SHAP-informed precedents plus constrained rationale generation.",
    },
    "retrieval_only": {
        "label": "Ablation 1: Retrieval-only, no SHAP",
        "description": "Precedent retrieval without SHAP contributions or SHAP-weighted alignment.",
    },
    "attribution_only": {
        "label": "Ablation 2: Attribution-only, no precedents",
        "description": "SHAP/attribution evidence without retrieved precedent records.",
    },
    "unconstrained": {
        "label": "Ablation 3: Unconstrained generation",
        "description": "Full evidence is provided, but strict grounding and hierarchy rules are removed.",
    },
}

STATE: Dict[str, Any] = {
    "case_base": None,
    "shap_scores": None,
    "holdout": None,
    "holdout_shap": None,
    "target_column": "",
    "feature_columns": [],
    "case_vectors": None,
    "holdout_vectors": None,
    "retrieval_mode": "reconstructed exported features",
    "shap_convention_warning": "",
    "api_key": "",
    "model": "gpt-4.1-mini",
    "prediction_goal": "",
    "include_baseline_signal": False,
    "variants": ["full_e2r2", "retrieval_only", "attribution_only", "unconstrained"],
    "individual_result": None,
    "batch_results": None,
    "batch_metrics": None,
    "batch_status": {
        "running": False,
        "completed": 0,
        "total": 0,
        "current_row": "",
        "current_variant": "",
        "message": "No batch is running.",
        "error": "",
        "finished": False,
    },
    "error": None,
}

STATE_LOCK = threading.Lock()


def dataframe_to_csv_bytes(df: pd.DataFrame) -> bytes:
    return df.to_csv(index=False).encode("utf-8-sig")


def infer_llm_role(prediction_goal: str, target_column: str) -> str:
    return (
        "You are an experienced domain analyst working in the field implied by the prediction goal below. "
        "You specialize in identifying cases at risk of the outcome of concern and explaining risk factors "
        "in practical, support-oriented language appropriate to that domain."
    )


def read_uploaded_table(file_obj: io.BytesIO) -> pd.DataFrame:
    name = getattr(file_obj, "name", "").lower()
    file_obj.seek(0)
    if name.endswith(".csv"):
        return pd.read_csv(file_obj)
    if name.endswith(".xlsx") or name.endswith(".xls"):
        return pd.read_excel(file_obj)
    raise ValueError("Unsupported file type. Upload a CSV, XLSX, or XLS file.")


def esc(value: Any) -> str:
    return html.escape("" if value is None else str(value), quote=True)


def parse_post(handler: BaseHTTPRequestHandler) -> cgi.FieldStorage:
    return cgi.FieldStorage(
        fp=handler.rfile,
        headers=handler.headers,
        environ={
            "REQUEST_METHOD": "POST",
            "CONTENT_TYPE": handler.headers.get("Content-Type", ""),
        },
    )


def form_get(form: cgi.FieldStorage, key: str, default: Any = "") -> Any:
    if key not in form:
        return default
    value = form[key]
    if isinstance(value, list):
        return [item.value for item in value]
    return value.value


def load_upload(field: Any) -> Optional[pd.DataFrame]:
    if field is None or not getattr(field, "filename", ""):
        return None
    data = field.file.read()
    file_obj = io.BytesIO(data)
    file_obj.name = field.filename
    return read_uploaded_table(file_obj)


def shap_convention_warning(shap_scores: pd.DataFrame) -> str:
    if "shap_output_units" not in shap_scores.columns:
        return (
            "This SHAP file does not say which model output was explained. "
            "For the updated prompt, use SHAP files regenerated by the latest main E2R2 app."
        )
    units = shap_scores["shap_output_units"].dropna().astype(str).str.lower().unique().tolist()
    if units and not any("positive_class" in unit for unit in units):
        return (
            "This SHAP file may use the older predicted-class SHAP convention. "
            "Regenerate the case base and SHAP scores in the latest main E2R2 app before running final experiments."
        )
    return ""


def model_option_tags(selected: str) -> str:
    return "\n".join(
        f"<option value='{esc(value)}'{' selected' if value == selected else ''}>{esc(label)} ({esc(value)})</option>"
        for value, label in OPENAI_LLM_MODELS
    )


def response_token_limit(model: str) -> int:
    if "pro" in model:
        return 6000
    if model in {"gpt-5-mini", "gpt-5-nano"}:
        return 3200
    if model.startswith("gpt-5") or model.startswith("o"):
        return 2400
    return 1200


def table_html(df: Optional[pd.DataFrame], max_rows: int = 20) -> str:
    if df is None or df.empty:
        return "<p class='muted'>No rows yet.</p>"
    return df.head(max_rows).to_html(index=False, classes="data-table", border=0, escape=True)


def infer_target_column(holdout: pd.DataFrame) -> str:
    columns = list(holdout.columns)
    if "baseline_predicted_outcome" in columns:
        idx = columns.index("baseline_predicted_outcome")
        if idx > 0:
            return columns[idx - 1]
    candidates = [c for c in columns if c.upper().endswith("STATUS") or "OUTCOME" in c.upper()]
    return candidates[-1] if candidates else ""


def feature_columns_for_retrieval(holdout: pd.DataFrame, target_column: str) -> List[str]:
    excluded = set(BASELINE_COLUMNS) | {"row_index", target_column}
    return [c for c in holdout.columns if c not in excluded]


def vector_columns(df: pd.DataFrame) -> List[str]:
    return [c for c in df.columns if str(c).startswith("vector_")]


def original_feature_for_encoded_column(
    encoded_column: str,
    feature_columns: List[str],
    categorical_columns: List[str],
) -> str:
    name = str(encoded_column)
    if name in feature_columns:
        return name
    for column in sorted(categorical_columns, key=len, reverse=True):
        if name == column or name.startswith(f"{column}_"):
            return column
    return name


def shap_similarity_weights(
    shap_scores: pd.DataFrame,
    encoded_columns: List[str],
    feature_columns: List[str],
    categorical_columns: List[str],
) -> Tuple[np.ndarray, str]:
    if shap_scores is None or "feature" not in shap_scores.columns or "abs_shap_score" not in shap_scores.columns:
        return np.ones(len(encoded_columns), dtype=float), "reconstructed unweighted features"
    importance_frame = shap_scores[["feature", "abs_shap_score"]].copy()
    importance_frame["feature"] = importance_frame["feature"].astype(str)
    importance_frame["abs_shap_score"] = pd.to_numeric(importance_frame["abs_shap_score"], errors="coerce")
    importance = (
        importance_frame
        .groupby("feature")["abs_shap_score"]
        .mean()
        .to_dict()
    )
    raw = np.asarray(
        [
            float(importance.get(original_feature_for_encoded_column(col, feature_columns, categorical_columns), 0.0))
            for col in encoded_columns
        ],
        dtype=float,
    )
    raw = np.nan_to_num(np.abs(raw), nan=0.0, posinf=0.0, neginf=0.0)
    if float(raw.sum()) <= 0:
        return np.ones(len(encoded_columns), dtype=float), "reconstructed unweighted features"
    weights = np.sqrt(raw / max(float(raw.mean()), 1e-12))
    weights = np.clip(weights, 0.25, 4.0)
    return weights.astype(float), "SHAP-weighted reconstructed features"


def build_retrieval_vectors(
    holdout: pd.DataFrame,
    case_base: pd.DataFrame,
    feature_columns: List[str],
    shap_scores: pd.DataFrame,
) -> Tuple[np.ndarray, np.ndarray, str]:
    features = holdout[feature_columns].copy()
    numeric_cols = [c for c in features.columns if pd.api.types.is_numeric_dtype(features[c])]
    categorical_cols = [c for c in features.columns if c not in numeric_cols]

    numeric = features[numeric_cols].copy() if numeric_cols else pd.DataFrame(index=features.index)
    for col in numeric.columns:
        numeric[col] = numeric[col].fillna(numeric[col].median())
        std = numeric[col].std()
        numeric[col] = 0 if not std or pd.isna(std) else (numeric[col] - numeric[col].mean()) / std
    categorical = (
        pd.get_dummies(features[categorical_cols].fillna("__missing__").astype(str), dummy_na=False)
        if categorical_cols
        else pd.DataFrame(index=features.index)
    )
    encoded = pd.concat([numeric, categorical], axis=1)
    weights, weighting_label = shap_similarity_weights(
        shap_scores,
        [str(c) for c in encoded.columns.tolist()],
        feature_columns,
        categorical_cols,
    )
    matrix = encoded.to_numpy(dtype=float)
    if len(weights) == matrix.shape[1]:
        matrix = matrix * weights
    norms = np.linalg.norm(matrix, axis=1, keepdims=True)
    norms[norms == 0] = 1
    holdout_vectors = matrix / norms
    row_to_position = {row_index: pos for pos, row_index in enumerate(holdout["row_index"].tolist())}
    case_positions = [row_to_position[idx] for idx in case_base["row_index"].tolist() if idx in row_to_position]
    if not case_positions:
        raise ValueError("None of the case-base row_index values were found in the holdout dataset.")
    return holdout_vectors, holdout_vectors[case_positions], weighting_label


def load_exported_vectors(
    holdout: pd.DataFrame,
    case_base: pd.DataFrame,
    holdout_vector_df: Optional[pd.DataFrame],
    case_vector_df: Optional[pd.DataFrame],
) -> Optional[Tuple[np.ndarray, np.ndarray]]:
    if holdout_vector_df is None or case_vector_df is None:
        return None
    h_cols = vector_columns(holdout_vector_df)
    c_cols = vector_columns(case_vector_df)
    if not h_cols or h_cols != c_cols:
        raise ValueError("Vector files must contain matching vector_ columns.")
    holdout_joined = holdout[["row_index"]].merge(
        holdout_vector_df[["row_index"] + h_cols], on="row_index", how="left"
    )
    case_joined = case_base[["case_id", "row_index"]].merge(
        case_vector_df[["case_id", "row_index"] + c_cols], on=["case_id", "row_index"], how="left"
    )
    if holdout_joined[h_cols].isna().any().any() or case_joined[c_cols].isna().any().any():
        raise ValueError("The vector files do not match the uploaded case base and holdout rows.")
    return holdout_joined[h_cols].to_numpy(dtype=float), case_joined[c_cols].to_numpy(dtype=float)


def prepare_loaded_data(
    case_base: pd.DataFrame,
    shap_scores: pd.DataFrame,
    holdout: pd.DataFrame,
    case_vectors_df: Optional[pd.DataFrame],
    holdout_vectors_df: Optional[pd.DataFrame],
    holdout_shap: Optional[pd.DataFrame],
) -> None:
    required_case = {"case_id", "row_index", "predicted_outcome", "confidence"}
    required_shap = {"case_id", "feature", "value", "shap_score", "abs_shap_score"}
    required_holdout = {"row_index", "baseline_predicted_outcome", "baseline_confidence"}
    missing = []
    if not required_case.issubset(case_base.columns):
        missing.append(f"case base missing: {sorted(required_case - set(case_base.columns))}")
    if not required_shap.issubset(shap_scores.columns):
        missing.append(f"SHAP scores missing: {sorted(required_shap - set(shap_scores.columns))}")
    if not required_holdout.issubset(holdout.columns):
        missing.append(f"holdout missing: {sorted(required_holdout - set(holdout.columns))}")
    if missing:
        raise ValueError("; ".join(missing))

    target_column = infer_target_column(holdout)
    feature_columns = feature_columns_for_retrieval(holdout, target_column)
    exact = load_exported_vectors(holdout, case_base, holdout_vectors_df, case_vectors_df)
    if exact is not None:
        holdout_vectors, case_vectors = exact
        retrieval_mode = "exported training-pipeline vectors"
    else:
        holdout_vectors, case_vectors, retrieval_mode = build_retrieval_vectors(
            holdout, case_base, feature_columns, shap_scores
        )
    STATE.update(
        {
            "case_base": case_base,
            "shap_scores": shap_scores,
            "holdout": holdout,
            "holdout_shap": holdout_shap,
            "target_column": target_column,
            "feature_columns": feature_columns,
            "holdout_vectors": holdout_vectors,
            "case_vectors": case_vectors,
            "retrieval_mode": retrieval_mode,
            "shap_convention_warning": shap_convention_warning(shap_scores),
            "individual_result": None,
            "batch_results": None,
            "batch_metrics": None,
            "batch_status": fresh_batch_status("No batch is running."),
        }
    )


def fresh_batch_status(message: str = "No batch is running.") -> Dict[str, Any]:
    return {
        "running": False,
        "completed": 0,
        "total": 0,
        "current_row": "",
        "current_variant": "",
        "message": message,
        "error": "",
        "finished": False,
    }


def set_batch_status(**updates: Any) -> None:
    with STATE_LOCK:
        status = dict(STATE.get("batch_status") or {})
        status.update(updates)
        STATE["batch_status"] = status


def get_batch_status() -> Dict[str, Any]:
    with STATE_LOCK:
        status = dict(STATE.get("batch_status") or {})
    total = int(status.get("total") or 0)
    completed = int(status.get("completed") or 0)
    status["percent"] = int(round((completed / total) * 100)) if total else 0
    return status


def call_openai(api_key: str, model: str, prompt: str) -> str:
    payload: Dict[str, Any] = {
        "model": model,
        "input": prompt,
        "max_output_tokens": response_token_limit(model),
    }
    if not model.startswith("gpt-5") and not model.startswith("o"):
        payload["temperature"] = 0.2
    request = Request(
        "https://api.openai.com/v1/responses",
        headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
        data=json.dumps(payload).encode("utf-8"),
        method="POST",
    )
    try:
        with urlopen(request, timeout=150) as response:
            data = json.loads(response.read().decode("utf-8"))
    except HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        try:
            detail = json.loads(detail).get("error", {}).get("message", detail)
        except Exception:
            pass
        raise RuntimeError(f"OpenAI API request failed ({exc.code}): {detail}") from exc
    if data.get("output_text"):
        return data["output_text"]
    chunks = []
    for item in data.get("output", []):
        for content in item.get("content", []):
            if content.get("type") in {"output_text", "text"}:
                chunks.append(content.get("text", ""))
    return "\n".join(chunks).strip()


def parse_llm_json(text: str) -> Dict[str, Any]:
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", text, re.DOTALL)
        if not match:
            return {}
        try:
            return json.loads(match.group(0))
        except json.JSONDecodeError:
            return {}


def retrieve_cases(row_index: Any, k: int) -> pd.DataFrame:
    case_base = STATE["case_base"]
    holdout = STATE["holdout"]
    holdout_vectors = STATE["holdout_vectors"]
    case_vectors = STATE["case_vectors"]
    row_to_position = {value: pos for pos, value in enumerate(holdout["row_index"].tolist())}
    if row_index not in row_to_position:
        raise ValueError(f"Holdout row_index {row_index} was not found.")
    vector = holdout_vectors[row_to_position[row_index]]
    rows = case_base.copy()
    rows["similarity"] = case_vectors @ vector
    rows = rows[rows["row_index"] != row_index]
    return rows.sort_values("similarity", ascending=False).head(k).reset_index(drop=True)


def feature_definition(feature: str) -> str:
    shap_scores = STATE["shap_scores"]
    if "definition" not in shap_scores.columns:
        return ""
    matches = shap_scores.loc[shap_scores["feature"].astype(str) == str(feature), "definition"].dropna()
    return "" if matches.empty else str(matches.iloc[0])


def feature_lines(row: pd.Series) -> str:
    target_column = STATE["target_column"]
    excluded = set(BASELINE_COLUMNS) | {"row_index", target_column}
    lines = []
    for feature, value in row.items():
        if feature in excluded:
            continue
        definition = feature_definition(feature)
        suffix = f" ({definition})" if definition else ""
        lines.append(f"- {feature}{suffix}: {value}")
    return "\n".join(lines)


def peer_blocks(retrieved: pd.DataFrame, include_shap: bool) -> str:
    shap_scores = STATE["shap_scores"]
    blocks = []
    for _, peer in retrieved.iterrows():
        header = (
            f"Case {peer.case_id}: outcome={peer.predicted_outcome}, "
            f"retrieval similarity={float(peer.similarity):.3f}"
        )
        if not include_shap:
            blocks.append(header)
            continue
        peer_shap = shap_scores[shap_scores["case_id"] == peer["case_id"]].sort_values("rank").head(5)
        units = (
            peer_shap["shap_output_units"].dropna().iloc[0]
            if "shap_output_units" in peer_shap.columns and not peer_shap["shap_output_units"].dropna().empty
            else "probability"
        )
        shap_lines = [
            f"  - {item.feature}: value={item.value}, SHAP contribution to positive-class probability={item.shap_score:.4f} ({units})"
            for item in peer_shap.itertuples()
        ]
        blocks.append("\n".join([header, *shap_lines]))
    return "\n".join(blocks)


def neighbor_distribution(retrieved: pd.DataFrame) -> str:
    counts = retrieved["predicted_outcome"].astype(str).value_counts()
    total = int(counts.sum())
    if total == 0:
        return "- No retrieved neighbors."
    lines = []
    for outcome, count in counts.items():
        percent = (count / total) * 100
        lines.append(f"- {outcome}: {count} of {total} retrieved neighbors ({percent:.1f}%)")
    return "\n".join(lines)


def shap_alignment(row: pd.Series, retrieved: pd.DataFrame) -> str:
    shap_scores = STATE["shap_scores"]
    relevant = shap_scores[shap_scores["case_id"].isin(retrieved["case_id"])].copy()
    rows = []
    for feature, group in relevant.groupby("feature"):
        mean_shap = group["shap_score"].mean()
        mean_abs = group["abs_shap_score"].mean()
        positive_count = int((group["shap_score"] > 0).sum())
        negative_count = int((group["shap_score"] < 0).sum())
        peer_values = group["value"].dropna().astype(str).value_counts().head(3)
        holdout_value = row.get(feature, "")
        matching_count = int((group["value"].astype(str) == str(holdout_value)).sum())
        if mean_shap > 0:
            direction = "increases positive-class probability"
        elif mean_shap < 0:
            direction = "decreases positive-class probability"
        else:
            direction = "has near-neutral direction"
        rows.append(
            {
                "mean_abs": mean_abs,
                "line": (
                    f"- {feature}: holdout={holdout_value}; peer values="
                    f"{', '.join([f'{value} ({count})' for value, count in peer_values.items()])}; "
                    f"mean SHAP={mean_shap:.4f}, mean |SHAP|={mean_abs:.4f}; "
                    f"{direction}; sign counts +/{positive_count}, -/{negative_count}; exact matches={matching_count}"
                ),
            }
        )
    rows = sorted(rows, key=lambda item: item["mean_abs"], reverse=True)[:5]
    return "\n".join(item["line"] for item in rows) or "- No SHAP alignment rows were available."


def recurring_top_predictors(row: pd.Series, retrieved: pd.DataFrame, per_case_top_k: int = 5, top_n: int = 5) -> str:
    shap_scores = STATE["shap_scores"]
    relevant = shap_scores[shap_scores["case_id"].isin(retrieved["case_id"])].copy()
    if "rank" in relevant.columns:
        relevant = relevant[relevant["rank"] <= per_case_top_k].copy()
    if relevant.empty:
        return "- No recurring top-predictor rows were available."
    total_cases = max(int(retrieved["case_id"].nunique()), 1)
    rows = []
    for feature, group in relevant.groupby("feature"):
        holdout_value = row.get(feature, "")
        peer_values = group["value"].dropna().astype(str).value_counts().head(3)
        mean_abs = float(group["abs_shap_score"].mean())
        mean_shap = float(group["shap_score"].mean())
        case_count = int(group["case_id"].nunique())
        if mean_shap > 0:
            direction = "usually increases positive-class probability"
        elif mean_shap < 0:
            direction = "usually decreases positive-class probability"
        else:
            direction = "has mixed overall direction"
        definition = feature_definition(feature)
        suffix = f" ({definition})" if definition else ""
        rows.append(
            {
                "case_count": case_count,
                "mean_abs": mean_abs,
                "line": (
                    f"- {feature}{suffix}: appears in {case_count}/{total_cases} retrieved cases' top {per_case_top_k} predictors; "
                    f"holdout={holdout_value}; precedent values={', '.join([f'{value} ({count})' for value, count in peer_values.items()])}; "
                    f"mean |SHAP|={mean_abs:.4f}; {direction}"
                ),
            }
        )
    rows = sorted(rows, key=lambda item: (item["case_count"], item["mean_abs"]), reverse=True)[:top_n]
    return "\n".join(item["line"] for item in rows)


def attribution_block(row_index: Any, retrieved: pd.DataFrame) -> Tuple[str, str]:
    holdout_shap = STATE.get("holdout_shap")
    if holdout_shap is not None and not holdout_shap.empty:
        key_col = "row_index" if "row_index" in holdout_shap.columns else "case_id" if "case_id" in holdout_shap.columns else ""
        if key_col:
            matches = holdout_shap[holdout_shap[key_col].astype(str) == str(row_index)].copy()
            if not matches.empty:
                matches = matches.sort_values("abs_shap_score", ascending=False).head(12)
                lines = [
                    f"- {item.feature}: value={getattr(item, 'value', '')}, SHAP contribution to positive-class probability={item.shap_score:.4f}, |SHAP|={item.abs_shap_score:.4f}"
                    for item in matches.itertuples()
                ]
                return "holdout_shap", "\n".join(lines)
    shap_scores = STATE["shap_scores"]
    relevant = shap_scores[shap_scores["case_id"].isin(retrieved["case_id"])].copy()
    if relevant.empty:
        return "none", "- No attribution rows were available."
    agg = (
        relevant.groupby("feature", as_index=False)
        .agg(mean_shap=("shap_score", "mean"), mean_abs_shap=("abs_shap_score", "mean"))
        .sort_values("mean_abs_shap", ascending=False)
        .head(12)
    )
    lines = [
        (
            f"- {row.feature}: mean SHAP across retrieved cases={row.mean_shap:.4f}, "
            f"mean |SHAP|={row.mean_abs_shap:.4f}; "
            f"{'increases' if row.mean_shap > 0 else 'decreases' if row.mean_shap < 0 else 'has neutral effect on'} "
            "positive-class probability"
        )
        for row in agg.itertuples()
    ]
    return "retrieved_precedent_shap_proxy", "\n".join(lines)


def labels_for_prompt() -> str:
    holdout = STATE["holdout"]
    target = STATE["target_column"]
    if target and target in holdout.columns:
        labels = sorted(holdout[target].dropna().astype(str).unique().tolist())
        if labels:
            return ", ".join(labels)
    if "baseline_predicted_outcome" in holdout.columns:
        labels = sorted(holdout["baseline_predicted_outcome"].dropna().astype(str).unique().tolist())
        if labels:
            return ", ".join(labels)
    return "domain labels"


def infer_positive_outcome_label(values: List[Any], prediction_goal: str) -> str:
    labels = []
    seen = set()
    for value in values:
        raw = str(value)
        normalized = normalize_label(value)
        if not normalized or normalized in seen:
            continue
        seen.add(normalized)
        labels.append((raw, normalized))
    if not labels:
        return ""
    for raw, normalized in labels:
        if normalized == "1":
            return raw
    numeric = []
    for raw, normalized in labels:
        try:
            numeric.append((raw, float(normalized)))
        except ValueError:
            pass
    if len(numeric) == len(labels) and numeric:
        return max(numeric, key=lambda item: item[1])[0]
    risk_terms = ["attrition", "churn", "default", "fraud", "readmission", "dropout", "risk", "positive", "yes", "true"]
    goal_text = normalize_label(prediction_goal)
    for raw, normalized in labels:
        if any(term in normalized for term in risk_terms):
            return raw
        if normalized and normalized in goal_text:
            return raw
    safe_terms = ["retained", "stay", "persist", "negative", "no", "false", "safe", "continue"]
    safe_norms = {normalized for _, normalized in labels if any(term in normalized for term in safe_terms)}
    if len(labels) == 2 and len(safe_norms) == 1:
        for raw, normalized in labels:
            if normalized not in safe_norms:
                return raw
    return labels[-1][0]


def positive_class_specification() -> Tuple[str, str]:
    holdout = STATE["holdout"]
    target = STATE["target_column"]
    prediction_goal = str(STATE.get("prediction_goal") or "").strip()
    values: List[Any] = []
    if holdout is not None and target and target in holdout.columns:
        values = holdout[target].dropna().astype(str).unique().tolist()
    elif holdout is not None and "baseline_predicted_outcome" in holdout.columns:
        values = holdout["baseline_predicted_outcome"].dropna().astype(str).unique().tolist()
    label = infer_positive_outcome_label(values, prediction_goal or target) if values else ""
    description = prediction_goal or (f"cases with outcome label {label}" if label else "the positive/risk outcome")
    return str(label), description


def baseline_block(row: pd.Series) -> str:
    return ""


def common_two_stage_intro(
    role: str,
    prediction_goal: str,
    target_column: str,
    positive_class_label: str,
    positive_class_description: str,
) -> str:
    return f"""{role}
You are using the E2R2 framework: Explain, Embed, Retrieve, and Reason.
E2R2 combines SHAP feature attributions, similarity-based precedent retrieval, and professional reasoning. The retrieved precedents come from a case base of correctly predicted, high-confidence holdout cases. Your job is to decide the outcome using precedent-based evidence, then verify that decision against an independent baseline machine-learning model's prediction.

Prediction goal:
{prediction_goal or f"Predict {target_column}."}

Positive class specification (CRITICAL - read this before any reasoning):
The positive class label for this task is provided explicitly below as positive_class_label. Use this label exactly as given. Do not infer the positive class from the retrieved precedent outcomes or from any other signal in the prompt. In particular:
- The positive class is NOT "whichever label the retrieved precedents happen to share." High-confidence retrieval can return all-one-class neighbors for either class, and that does not change which label is positive.
- A precedent outcome value equal to positive_class_label means that precedent is a positive-class case. A precedent outcome value not equal to positive_class_label means that precedent is a negative-class case.
- "pos_share" in the decision rule is the share of retrieved precedents whose outcome equals positive_class_label, regardless of which label that happens to be (0, 1, "churn", "default", etc.).
- All SHAP values are explained against probability of positive_class_label, as stated in the SHAP interpretation section below.

positive_class_label: {positive_class_label}
positive_class_description: {positive_class_description}

Reasoning workflow:
You will produce the final verdict in two internal stages. Complete Stage 1 fully before considering Stage 2. Do not allow knowledge of the baseline model's prediction (shown in the Stage 2 inputs) to influence your Stage 1 reasoning.
"""


def common_stage2_block(baseline_predicted_outcome: Any, baseline_confidence: Any) -> str:
    return f"""
=================================================================
STAGE 2 - BASELINE-MODEL VERIFICATION
=================================================================

Now consult the baseline machine-learning model's prediction shown in the Stage 2 inputs. The baseline model was trained independently of the precedent retrieval and SHAP attribution pipeline, so its prediction is a largely independent signal. When both signals agree, the Stage 1 verdict is reliable. When they disagree, the resolution depends on how confident the baseline is.

Critical clarifications before applying the rules:
- baseline_predicted_outcome is a HARD CLASS LABEL (e.g., 0 or 1, "positive" or "negative"). It is not a probability. Use it only as a label.
- baseline_confidence is a number between 0.50 and 1.00 that expresses how confident the baseline is in the class it predicted. A baseline_confidence of 0.5163 still means the baseline predicts its stated class - just weakly. It does NOT mean the baseline is undecided between classes.
- "Agreement" is a strict equality check between two labels. It does not depend on any probability or confidence value. baseline_confidence near 0.50 does NOT make agreement false.

Step 1 - Determine agreement.
Compare two values:
- stage1_verdict (the class label you fixed at the end of Stage 1; e.g., 1)
- baseline_predicted_outcome (the class label provided in the Stage 2 input; e.g., 1)

If these two labels are identical, then agreement = TRUE. If they are different, agreement = FALSE. Do not consult baseline_confidence or any other value when determining agreement.

Worked examples:
- stage1_verdict = 1, baseline_predicted_outcome = 1, baseline_confidence = 0.52 -> agreement = TRUE (both predict the same class; the low confidence does not change this).
- stage1_verdict = 1, baseline_predicted_outcome = 1, baseline_confidence = 0.99 -> agreement = TRUE.
- stage1_verdict = 1, baseline_predicted_outcome = 0, baseline_confidence = 0.55 -> agreement = FALSE.
- stage1_verdict = 0, baseline_predicted_outcome = 1, baseline_confidence = 0.80 -> agreement = FALSE.

Step 2 - Compute baseline_p_positive (for output transparency only; do NOT use this in the verification rules).
- If baseline_predicted_outcome equals positive_class_label, baseline_p_positive = baseline_confidence.
- If baseline_predicted_outcome does not equal positive_class_label, baseline_p_positive = 1 - baseline_confidence.

Step 3 - Apply the verification rules in order. Stop at the first rule that fires.

Rule A - Agreement. If agreement is TRUE (as determined in Step 1), keep the Stage 1 verdict and confidence unchanged. final_verdict = stage1_verdict. final_confidence = stage1_confidence. Do not consider baseline_confidence in this rule - agreement alone fires Rule A regardless of how confident or unconfident the baseline is.

Rule B - Confident baseline override. If agreement is FALSE AND baseline_confidence is at least 0.70, override to match the baseline. final_verdict = baseline_predicted_outcome. final_confidence = moderate (never high under override, since two independent signals disagreed). This rule applies symmetrically - a confident baseline whose predicted label is not positive_class_label overrides a Stage 1 positive verdict toward the negative class, and a confident baseline whose predicted label equals positive_class_label overrides a Stage 1 negative verdict toward the positive class.

Rule C - Weak baseline, keep Stage 1. If agreement is FALSE AND baseline_confidence is below 0.60, keep the Stage 1 verdict. final_verdict = stage1_verdict. final_confidence = stage1_confidence, but capped at moderate (downgrade high to moderate; leave moderate and low unchanged).

Rule D - Borderline disagreement. If agreement is FALSE AND baseline_confidence is between 0.60 and 0.70 (inclusive on the lower bound, exclusive on the upper), keep the Stage 1 verdict but downgrade final_confidence to low. Note explicitly in the final rationale that the baseline model disagreed at borderline confidence.

Do not invoke any rule other than the four above. Do not override based on the Stage 1 rationale text or the Stage 1 confidence - only the agreement check and the baseline_confidence value drive the verification.

Final rationale composition:
- If Rule A fired, the final rationale is the Stage 1 rationale, with a one-sentence note that the baseline model agreed (state baseline_confidence). The note should affirm agreement even if baseline_confidence is low; a low-confidence agreement is still agreement.
- If Rule B fired, the final rationale should keep the Stage 1 evidence summary but append a sentence explaining that the baseline model disagreed at confident strength (state baseline_confidence) and that the verification step adopted the baseline verdict.
- If Rule C fired, the final rationale is the Stage 1 rationale, with a one-sentence note that the baseline model disagreed at low confidence (state baseline_confidence) and was not strong enough to override.
- If Rule D fired, the final rationale is the Stage 1 rationale, with a one-sentence note that the baseline model disagreed at borderline confidence (state baseline_confidence), which was not sufficient to override but reduced confidence in the final verdict.

=================================================================
INPUTS
=================================================================

Baseline model output:
- baseline_predicted_outcome: {baseline_predicted_outcome}
- baseline_confidence: {float(baseline_confidence):.4f}
"""


def common_output_block(stage1_rationale_contract: str) -> str:
    return f"""
=================================================================
OUTPUT
=================================================================

Return this JSON object:
{{
  "stage1_predicted_outcome": "one of the domain labels",
  "stage1_confidence_level": "low | moderate | high",
  "stage1_rationale": "{stage1_rationale_contract}",
  "agreement": true | false,
  "baseline_p_positive": <numeric value between 0 and 1>,
  "verification_rule_applied": "A | B | C | D",
  "final_predicted_outcome": "one of the domain labels",
  "final_confidence_level": "low | moderate | high",
  "final_rationale": "the Stage 1 rationale plus the appropriate verification note as described in the Final rationale composition section"
}}

Base the rationale on the evidence shown in the prompt. The true outcome is not provided for reasoning.
"""


def build_prompt(variant: str, row: pd.Series, retrieved: pd.DataFrame, neighbors: int) -> Tuple[str, str]:
    target_column = STATE["target_column"]
    prediction_goal = STATE["prediction_goal"]
    role = infer_llm_role(prediction_goal, target_column)
    labels = labels_for_prompt()
    positive_class_label, positive_class_description = positive_class_specification()
    n_pos = (
        int((retrieved["predicted_outcome"].astype(str) == str(positive_class_label)).sum())
        if positive_class_label
        else 0
    )
    n_total = int(len(retrieved))
    pos_share = (100.0 * n_pos / n_total) if n_total else 0.0
    top_similarity = float(retrieved["similarity"].max()) if not retrieved.empty else 0.0
    common_header = f"""{role}

Prediction goal:
{prediction_goal or f"Predict {target_column}."}

Candidate labels:
{labels}

Holdout case profile:
{feature_lines(row)}
"""
    json_contract = """Return valid JSON only, with no Markdown:
{
  "predicted_outcome": "one of the candidate labels",
  "confidence_level": "low | moderate | high",
  "rationale": "one professional paragraph"
}
"""
    if variant == "retrieval_only":
        baseline_predicted_outcome = row.get("baseline_predicted_outcome", "")
        baseline_confidence = row.get("baseline_confidence", "")
        prompt = f"""{common_two_stage_intro(role, prediction_goal, target_column, positive_class_label, positive_class_description)}
=================================================================
STAGE 1 - RETRIEVAL-ONLY PRECEDENT REASONING
=================================================================

MISQ ablation condition: Retrieval-only E2R2 without SHAP alignment.
Use the retrieved precedent cases and similarity scores, but do not use SHAP contributions or SHAP-weighted alignment. This condition tests whether precedent retrieval alone is sufficient for prediction and explanation.

Reasoning guidance:
Use your best professional judgment to predict the outcome from the evidence shown below: the holdout case profile, the retrieved precedent cases, their outcomes, and their similarity scores.

Stage 1 rules:
1. Let N be the total number of retrieved precedents and let n_pos be the count of those precedents whose outcome equals positive_class_label. Compute pos_share = n_pos / N as a percentage.
2. Use retrieved precedent outcomes and similarity scores as the main evidence for Stage 1. Do not use SHAP contributions or SHAP-weighted alignment in this ablation.
3. Do not simply majority-vote retrieved cases; use similarity strength and any visible feature resemblance in the prompt when helpful.
4. If evidence is mixed, explain the uncertainty clearly.
5. Do not invent facts not shown in the prompt.

Stage 1 confidence calibration:
- High: pos_share >= 80% AND top retrieval similarity >= 0.85 AND the retrieved precedent signal is strongly one-directional.
- Moderate: retrieved precedent signals mostly point in one direction, but similarity or outcome consistency is softer.
- Low: pos_share is between 20% and 60%, OR top retrieval similarity < 0.75, OR the retrieved precedent evidence is mixed.

At the end of Stage 1, internally fix three values before reading any Stage 2 input:
- stage1_verdict (the positive or negative class label)
- stage1_confidence (low | moderate | high)
- stage1_rationale (a detailed paragraph as described in the JSON schema below)

=================================================================
INPUTS
=================================================================

Holdout case profile:
{feature_lines(row)}

Retrieved E2R2 precedent cases:
{peer_blocks(retrieved, include_shap=False)}

Precedent outcome counts:
- N={n_total}
- n_pos={n_pos}
- pos_share={pos_share:.1f}%
{neighbor_distribution(retrieved)}
- top retrieval similarity={top_similarity:.3f}
{common_stage2_block(baseline_predicted_outcome, baseline_confidence)}
{common_output_block('one detailed professional paragraph that (a) uses the holdout profile plus retrieved precedent outcomes and similarity scores, (b) states N, n_pos, and pos_share, (c) notes that this was the retrieval-only ablation without SHAP evidence, and (d) explains how that evidence led to the Stage 1 verdict')}
"""
        return prompt, "retrieval_without_shap"

    if variant == "attribution_only":
        source, attribution = attribution_block(row.get("row_index", ""), retrieved)
        baseline_predicted_outcome = row.get("baseline_predicted_outcome", "")
        baseline_confidence = row.get("baseline_confidence", "")
        prompt = f"""{common_two_stage_intro(role, prediction_goal, target_column, positive_class_label, positive_class_description)}
=================================================================
STAGE 1 - ATTRIBUTION-ONLY REASONING
=================================================================

MISQ ablation condition: Attribution-only E2R2 without precedent retrieval.
Use only the holdout profile and attribution evidence below. Do not reference or infer specific historical precedent cases. This condition tests the value of evidence grounding through precedents.

Reasoning guidance:
Use your best professional judgment to predict the outcome from the holdout profile and attribution evidence only.

Stage 1 rules:
1. This ablation withholds retrieved precedent records. For transparency, set N=0, n_pos=0, and pos_share=0% in the Stage 1 rationale, and explicitly note that precedent counts were unavailable in this condition.
2. Interpret attribution evidence against the probability of positive_class_label: positive SHAP increases it, negative SHAP decreases it.
3. Give the greatest weight to the largest absolute SHAP contributors and explain whether they support or weaken the positive outcome.
4. Do not claim that a similar prior case exists.
5. If attribution evidence source is proxy evidence from retrieved-case SHAP rather than true holdout SHAP, state that uncertainty clearly in the rationale.
6. Do not invent facts not shown in the prompt.

Stage 1 confidence calibration:
- High: the strongest attribution signals are large, coherent, and all point in the same direction, and the evidence source is direct holdout SHAP.
- Moderate: the strongest attribution signals mostly point in one direction, but magnitude, coherence, or source quality is softer.
- Low: attribution signals are mixed, weak, or proxy-based enough to create substantial uncertainty.

At the end of Stage 1, internally fix three values before reading any Stage 2 input:
- stage1_verdict (the positive or negative class label)
- stage1_confidence (low | moderate | high)
- stage1_rationale (a detailed paragraph as described in the JSON schema below)

=================================================================
INPUTS
=================================================================

Holdout case profile:
{feature_lines(row)}

Attribution evidence source:
{source}

Attribution evidence:
{attribution}
{common_stage2_block(baseline_predicted_outcome, baseline_confidence)}
{common_output_block('one detailed professional paragraph that (a) uses the holdout profile plus attribution evidence only, (b) states N=0, n_pos=0, and pos_share=0% because retrieved precedent counts were not available in this ablation, (c) notes whether the attribution source was direct holdout SHAP or a proxy source, and (d) explains how that evidence led to the Stage 1 verdict')}
"""
        return prompt, f"attribution_source={source}"

    if variant == "unconstrained":
        baseline_predicted_outcome = row.get("baseline_predicted_outcome", "")
        baseline_confidence = row.get("baseline_confidence", "")
        prompt = f"""{role}
You are using the E2R2 framework: Explain, Embed, Retrieve, and Reason.
E2R2 combines SHAP feature attributions, similarity-based precedent retrieval, and professional reasoning. The retrieved precedents come from a case base of correctly predicted, high-confidence holdout cases.

Prediction goal:
{prediction_goal or f"Predict {target_column}."}

Positive class specification (CRITICAL - read this before any reasoning):
The positive class label for this task is provided explicitly below as positive_class_label. Use this label exactly as given. Do not infer the positive class from the retrieved precedent outcomes or from any other signal in the prompt.
- A precedent outcome value equal to positive_class_label means that precedent is a positive-class case.
- A precedent outcome value not equal to positive_class_label means that precedent is a negative-class case.
- "pos_share" is the share of retrieved precedents whose outcome equals positive_class_label.
- All SHAP values are explained against probability of positive_class_label.

positive_class_label: {positive_class_label}
positive_class_description: {positive_class_description}

=================================================================
MISQ ABLATION CONDITION - UNCONSTRAINED GENERATION
=================================================================

Use your best professional judgment from all evidence shown below: the holdout case profile, retrieved precedent cases, precedent outcomes, similarity scores, top SHAP predictors, SHAP-weighted alignment summary, precedent outcome counts, and baseline model output.

This condition intentionally removes the strict E2R2 decision hierarchy, structural-risk checklist, and baseline-model verification rules. The baseline prediction and confidence are provided as one additional piece of evidence. You may use, discount, or disagree with the baseline signal in whatever way seems most justified by the total evidence.

General guardrails:
- Let N be the total number of retrieved precedents and let n_pos be the count whose outcome equals positive_class_label. Compute pos_share = n_pos / N as a percentage.
- Interpret SHAP evidence against the probability of positive_class_label: positive SHAP increases it, negative SHAP decreases it, and larger absolute values indicate stronger model contributions.
- Precedent outcome counts may inform your reasoning, but do not rely on majority vote alone.
- Keep the rationale grounded in the evidence shown in the prompt and do not invent facts.
- Because this is an unconstrained ablation, do not apply any formal Stage 2 baseline override rule.

Confidence guidance:
- High: the available evidence sources point strongly in the same direction.
- Moderate: most evidence points in one direction, but one source of evidence is softer or mixed.
- Low: the evidence is materially mixed, contradictory, weak, or the baseline signal conflicts with the precedent/SHAP evidence.

=================================================================
INPUTS
=================================================================

Holdout case profile:
{feature_lines(row)}

Retrieved E2R2 precedent cases:
{peer_blocks(retrieved, include_shap=True)}

Recurring top predictors across retrieved precedents:
{recurring_top_predictors(row, retrieved, per_case_top_k=5, top_n=5)}

SHAP-weighted alignment summary across retrieved cases:
{shap_alignment(row, retrieved)}

Precedent outcome counts:
- N={n_total}
- n_pos={n_pos}
- pos_share={pos_share:.1f}%
{neighbor_distribution(retrieved)}
- top retrieval similarity={top_similarity:.3f}

Baseline model output:
- baseline_predicted_outcome: {baseline_predicted_outcome}
- baseline_confidence: {float(baseline_confidence):.4f}

=================================================================
OUTPUT
=================================================================

Return this JSON object:
{{
  "stage1_predicted_outcome": "not applicable",
  "stage1_confidence_level": "not applicable",
  "stage1_rationale": "not applicable",
  "agreement": null,
  "baseline_p_positive": null,
  "verification_rule_applied": "unconstrained",
  "final_predicted_outcome": "one of the domain labels",
  "final_confidence_level": "low | moderate | high",
  "final_rationale": "one detailed professional paragraph that (a) compares the holdout case with the retrieved precedents using the available SHAP and precedent evidence, (b) states N, n_pos, and pos_share, (c) explains how the baseline prediction and confidence were considered as flexible evidence, (d) notes that this was the unconstrained-generation ablation without formal baseline verification rules, and (e) explains how the combined evidence led to the final verdict"
}}

Base the rationale on the evidence shown in the prompt. The true outcome is not provided for reasoning.
"""
        return prompt, "unconstrained_generation"

    baseline_predicted_outcome = row.get("baseline_predicted_outcome", "")
    baseline_confidence = row.get("baseline_confidence", "")
    prompt = f"""MISQ condition: Full E2R2.
You are an experienced domain analyst working in the field implied by the prediction goal below. You specialize in identifying cases at risk of the outcome of concern and explaining risk factors in practical, support-oriented language appropriate to that domain.
You are using the E2R2 framework: Explain, Embed, Retrieve, and Reason.
E2R2 combines SHAP feature attributions, similarity-based precedent retrieval, and professional reasoning. The retrieved precedents come from a case base of correctly predicted, high-confidence holdout cases. Your job is to decide the outcome using precedent-based evidence, then verify that decision against an independent baseline machine-learning model's prediction.

Prediction goal:
{prediction_goal or f"Predict {target_column}."}

Positive class specification (CRITICAL — read this before any reasoning):
The positive class label for this task is provided explicitly below as positive_class_label. Use this label exactly as given. Do not infer the positive class from the retrieved precedent outcomes or from any other signal in the prompt. In particular:
- The positive class is NOT "whichever label the retrieved precedents happen to share." High-confidence retrieval can return all-one-class neighbors for either class, and that does not change which label is positive.
- A precedent outcome value equal to positive_class_label means that precedent is a positive-class case. A precedent outcome value not equal to positive_class_label means that precedent is a negative-class case.
- "pos_share" in the decision rule is the share of retrieved precedents whose outcome equals positive_class_label, regardless of which label that happens to be (0, 1, "churn", "default", etc.).
- All SHAP values are explained against probability of positive_class_label, as stated in the SHAP interpretation section below.

positive_class_label: {positive_class_label}
positive_class_description: {positive_class_description}

Reasoning workflow:
You will produce the final verdict in two internal stages. Complete Stage 1 fully before considering Stage 2. Do not allow knowledge of the baseline model's prediction (shown in the Stage 2 inputs) to influence your Stage 1 reasoning.

=================================================================
STAGE 1 — PRECEDENT-BASED REASONING
=================================================================

Reasoning guidance:
Use your best professional judgment to predict the outcome from the evidence shown below: the holdout case profile, the retrieved precedent cases, their outcomes, their similarity scores, and their top SHAP predictors.

Detailed comparison task:
- Identify the most important predictors that recur across the retrieved precedents' top 5 SHAP predictors.
- Start from the recurring top-predictor patterns, then compare the holdout case against the precedents predictor by predictor using the exact values shown when helpful.
- Explain whether the holdout case matches the precedent pattern, differs in a meaningful way, or shows mixed evidence on those predictors.
- Highlight critical differences on the strongest predictors, especially when the holdout case shows a protective pattern where positive precedents showed risk, or vice versa.
- If several predictors reflect the same underlying issue, treat them as one cluster rather than counting them as separate concerns.
- Use that comparison, together with precedent outcomes and similarity scores, to reach the Stage 1 verdict — following the decision rule below.

Decision rule (apply before writing the Stage 1 rationale):
1. Let N be the total number of retrieved precedents and let n_pos be the count of those precedents whose outcome equals positive_class_label (as specified at the top of the prompt — do not re-infer this from the precedent outcomes). Compute pos_share = n_pos / N, expressed as a percentage. If all retrieved precedents share an outcome that is not equal to positive_class_label, then n_pos = 0 and pos_share = 0%; this is a strong negative signal, not a positive one.
2. If pos_share >= 60%, the default Stage 1 verdict is positive. You may only override this default to a negative verdict if ALL of the following are true:
   (a) The holdout case shows a clearly protective pattern on the strongest recurring SHAP predictor (the one with the largest mean |SHAP|) — meaning the holdout value crosses into a clearly healthy range on that variable, not merely a relatively-better range than the precedent values.
   (b) The holdout also shows a clearly protective pattern on at least one other top-3 recurring predictor.
   (c) The holdout does not exhibit any late-stage disengagement or acute-risk signal of the kind described in the structural-risk checklist below.
   If you override the default, state the override explicitly in the Stage 1 rationale and name each condition you relied on.
3. If pos_share <= 20%, the default Stage 1 verdict is negative. You may only override to a positive verdict if the holdout shows a clear, high-leverage leading indicator of the positive outcome (e.g., a behavior, status, or value that is widely understood in the domain as a near-certain precursor of the outcome — see the structural-risk checklist below for how to recognize one).
4. If pos_share is between 20% and 60% (exclusive of both bounds), treat as borderline and resolve using the structural-risk checklist below.

Borderline structural-risk checklist (apply only when pos_share is in the borderline band between 20% and 60% exclusive, OR when pos_share is between 60% and 80% inclusive, OR when the top retrieval similarity across the retrieved neighbors is below 0.78):

A "structural-risk marker" is a predictor value in the holdout case that, in domain knowledge or in the recurring SHAP pattern of the case base, is a strong leading indicator of the positive outcome on its own. Identify markers using the following heuristics in order:
- Any predictor that appears in the top 5 SHAP list of at least 80% of the retrieved precedents, where the holdout's value matches the precedent cluster's risk-direction value (e.g., the same categorical level, or a numeric value in the same risk-side range).
- Any predictor in the holdout case that, by standard domain understanding, indicates an actively unfolding adverse event, withdrawal of support, missed obligation, or break in a normally-continuous process. These are typically the highest-leverage markers even when not present in the retrieved SHAP lists.
- Any predictor whose value sits past a well-understood absolute risk threshold for the domain (e.g., a performance or health metric below a level commonly treated as concerning), regardless of how the holdout compares to the precedent values.

Count how many such markers are present in the holdout. If 2 or more markers are present, lean toward the positive verdict. If 0 or 1 markers are present, lean toward the negative verdict. Name explicitly in the Stage 1 rationale which markers triggered, which heuristic identified each, and which did not trigger.

SHAP interpretation:
- All SHAP values are explained against the probability of positive_class_label (as specified at the top of the prompt), not against each precedent's own outcome.
- A positive SHAP contribution increases the modeled probability of positive_class_label; a negative SHAP contribution decreases it.
- Larger absolute SHAP values indicate stronger model contributions.

Cautions when comparing holdout values to precedent values:
- A holdout value that is better than the precedent cluster but still in an absolute risk zone is NOT protective. If the precedents have very extreme risk-side values on a key predictor and the holdout has a moderately-less-extreme but still risk-side value, treat this as a milder version of the same risk pattern, not as a protective signal.
- Only call a difference "protective" when the holdout value crosses into a clearly healthy or low-risk range on that variable by standard domain understanding, not merely when it is relatively better than the neighbors. State the healthy range you are using when you invoke protection.
- Late-stage or behavioral signals (e.g., a discontinuation, a missed step in a normally-continuous process, a withdrawal of support, an acute event) typically outweigh upstream profile differences. If such a signal is present in the holdout, it should generally not be overridden by a more favorable value on an upstream predictor.

Stage 1 confidence calibration (apply after determining the Stage 1 verdict):
- High: pos_share >= 80% AND top retrieval similarity >= 0.85 AND the holdout matches the precedent cluster on the strongest recurring SHAP predictor's absolute range (not just its direction). OR, for a negative verdict: pos_share = 0% AND no structural-risk-checklist markers are present AND top similarity >= 0.80.
- Moderate: precedents and structural signals point the same direction, but one of the high-confidence conditions above is missing (e.g., similarity is lower, or the holdout's value on the strongest predictor sits in a softer-but-still-aligned range).
- Low: precedent signal and structural-risk checklist disagree, OR top similarity < 0.75, OR pos_share is in the borderline band (between 20% and 60% exclusive) with mixed feature evidence, OR the decision rule above required an explicit override.

At the end of Stage 1, internally fix three values before reading any Stage 2 input:
- stage1_verdict (the positive or negative class label)
- stage1_confidence (low | moderate | high)
- stage1_rationale (a detailed paragraph as described in the JSON schema below)

=================================================================
STAGE 2 — BASELINE-MODEL VERIFICATION
=================================================================

Now consult the baseline machine-learning model's prediction shown in the Stage 2 inputs. The baseline model was trained independently of the precedent retrieval and SHAP attribution pipeline, so its prediction is a largely independent signal. When both signals agree, the Stage 1 verdict is reliable. When they disagree, the resolution depends on how confident the baseline is.

Critical clarifications before applying the rules:
- baseline_predicted_outcome is a HARD CLASS LABEL (e.g., 0 or 1, "positive" or "negative"). It is not a probability. Use it only as a label.
- baseline_confidence is a number between 0.50 and 1.00 that expresses how confident the baseline is in the class it predicted. A baseline_confidence of 0.5163 still means the baseline predicts its stated class — just weakly. It does NOT mean the baseline is undecided between classes.
- "Agreement" is a strict equality check between two labels. It does not depend on any probability or confidence value. baseline_confidence near 0.50 does NOT make agreement false.

Step 1 — Determine agreement.
Compare two values:
- stage1_verdict (the class label you fixed at the end of Stage 1; e.g., 1)
- baseline_predicted_outcome (the class label provided in the Stage 2 input; e.g., 1)

If these two labels are identical, then agreement = TRUE. If they are different, agreement = FALSE. Do not consult baseline_confidence or any other value when determining agreement.

Worked examples:
- stage1_verdict = 1, baseline_predicted_outcome = 1, baseline_confidence = 0.52 → agreement = TRUE (both predict the same class; the low confidence does not change this).
- stage1_verdict = 1, baseline_predicted_outcome = 1, baseline_confidence = 0.99 → agreement = TRUE.
- stage1_verdict = 1, baseline_predicted_outcome = 0, baseline_confidence = 0.55 → agreement = FALSE.
- stage1_verdict = 0, baseline_predicted_outcome = 1, baseline_confidence = 0.80 → agreement = FALSE.

Step 2 — Compute baseline_p_positive (for output transparency only; do NOT use this in the verification rules).
- If baseline_predicted_outcome equals positive_class_label, baseline_p_positive = baseline_confidence.
- If baseline_predicted_outcome does not equal positive_class_label, baseline_p_positive = 1 - baseline_confidence.

Step 3 — Apply the verification rules in order. Stop at the first rule that fires.

Rule A — Agreement. If agreement is TRUE (as determined in Step 1), keep the Stage 1 verdict and confidence unchanged. final_verdict = stage1_verdict. final_confidence = stage1_confidence. Do not consider baseline_confidence in this rule — agreement alone fires Rule A regardless of how confident or unconfident the baseline is.
Rule B — Confident baseline override. If agreement is FALSE AND baseline_confidence is at least 0.70, override to match the baseline. final_verdict = baseline_predicted_outcome. final_confidence = moderate (never high under override, since two independent signals disagreed). This rule applies symmetrically — a confident baseline whose predicted label is not positive_class_label overrides a Stage 1 positive verdict toward the negative class, and a confident baseline whose predicted label equals positive_class_label overrides a Stage 1 negative verdict toward the positive class.
Rule C — Weak baseline, keep Stage 1. If agreement is FALSE AND baseline_confidence is below 0.60, keep the Stage 1 verdict. final_verdict = stage1_verdict. final_confidence = stage1_confidence, but capped at moderate (downgrade high to moderate; leave moderate and low unchanged).
Rule D — Borderline disagreement. If agreement is FALSE AND baseline_confidence is between 0.60 and 0.70 (inclusive on the lower bound, exclusive on the upper), keep the Stage 1 verdict but downgrade final_confidence to low. Note explicitly in the final rationale that the baseline model disagreed at borderline confidence.

Do not invoke any rule other than the four above. Do not override based on the Stage 1 rationale text or the Stage 1 confidence — only the agreement check and the baseline_confidence value drive the verification.

Final rationale composition:
- If Rule A fired, the final rationale is the Stage 1 rationale, with a one-sentence note that the baseline model agreed (state baseline_confidence). The note should affirm agreement even if baseline_confidence is low; a low-confidence agreement is still agreement.
- If Rule B fired, the final rationale should keep the Stage 1 evidence summary but append a sentence explaining that the baseline model disagreed at confident strength (state baseline_confidence) and that the verification step adopted the baseline verdict.
- If Rule C fired, the final rationale is the Stage 1 rationale, with a one-sentence note that the baseline model disagreed at low confidence (state baseline_confidence) and was not strong enough to override.
- If Rule D fired, the final rationale is the Stage 1 rationale, with a one-sentence note that the baseline model disagreed at borderline confidence (state baseline_confidence), which was not sufficient to override but reduced confidence in the final verdict.

=================================================================
INPUTS
=================================================================

Holdout case profile:
{feature_lines(row)}

Retrieved E2R2 precedent cases:
{peer_blocks(retrieved, include_shap=True)}

Recurring top predictors across retrieved precedents:
{recurring_top_predictors(row, retrieved, per_case_top_k=5, top_n=5)}

SHAP-weighted alignment summary across retrieved cases:
{shap_alignment(row, retrieved)}

Precedent outcome counts:
- N={n_total}
- n_pos={n_pos}
- pos_share={pos_share:.1f}%
{neighbor_distribution(retrieved)}
- top retrieval similarity={top_similarity:.3f}

Baseline model output:
- baseline_predicted_outcome: {baseline_predicted_outcome}
- baseline_confidence: {float(baseline_confidence):.4f}

=================================================================
OUTPUT
=================================================================

Return this JSON object:
{{
  "stage1_predicted_outcome": "one of the domain labels",
  "stage1_confidence_level": "low | moderate | high",
  "stage1_rationale": "one detailed professional paragraph that (a) compares the holdout case with the retrieved precedents on the recurring top SHAP predictors, (b) states N, n_pos, and pos_share, and names which branch of the Stage 1 decision rule applied, (c) lists which structural-risk-checklist markers were checked and which triggered when applicable, and (d) explains how that combined evidence led to the Stage 1 verdict",
  "agreement": true | false,
  "baseline_p_positive": <numeric value between 0 and 1>,
  "verification_rule_applied": "A | B | C | D",
  "final_predicted_outcome": "one of the domain labels",
  "final_confidence_level": "low | moderate | high",
  "final_rationale": "the Stage 1 rationale plus the appropriate verification note as described in the Final rationale composition section"
}}
Base the rationale on the evidence shown in the prompt. The true outcome is not provided for reasoning.
"""
    return prompt, "full_e2r2"


def normalize_label(value: Any) -> str:
    if pd.isna(value):
        return ""
    text = str(value).strip()
    if text.endswith(".0"):
        text = text[:-2]
    return text.lower()


def run_prediction_for_row(row_index: Any, variant: str, neighbors: int) -> Dict[str, Any]:
    api_key = STATE["api_key"]
    if not api_key:
        raise ValueError("Enter and save your OpenAI API key first.")
    holdout = STATE["holdout"]
    row = holdout.loc[holdout["row_index"] == row_index].iloc[0]
    retrieved = retrieve_cases(row_index, neighbors)
    prompt, ablation_notes = build_prompt(variant, row, retrieved, neighbors)
    raw = call_openai(api_key, STATE["model"], prompt)
    parsed = parse_llm_json(raw)
    actual = row.get(STATE["target_column"], "")
    predicted = parsed.get("final_predicted_outcome", parsed.get("predicted_outcome", ""))
    correct = normalize_label(actual) == normalize_label(predicted) if normalize_label(actual) else ""
    return {
        "row_index": row_index,
        "variant": variant,
        "variant_label": ABLATION_VARIANTS[variant]["label"],
        "actual_outcome": actual,
        "baseline_predicted_outcome": row.get("baseline_predicted_outcome", ""),
        "baseline_confidence": row.get("baseline_confidence", ""),
        "baseline_positive_probability": row.get("baseline_positive_probability", ""),
        "stage1_predicted_outcome": parsed.get("stage1_predicted_outcome", ""),
        "stage1_confidence_level": parsed.get("stage1_confidence_level", ""),
        "stage1_rationale": parsed.get("stage1_rationale", ""),
        "agreement": parsed.get("agreement", ""),
        "baseline_p_positive": parsed.get("baseline_p_positive", ""),
        "verification_rule_applied": parsed.get("verification_rule_applied", ""),
        "llm_predicted_outcome": predicted,
        "llm_confidence_level": parsed.get("final_confidence_level", parsed.get("confidence_level", "")),
        "llm_rationale": parsed.get("final_rationale", parsed.get("rationale", "")),
        "correct": correct,
        "ablation_notes": ablation_notes,
        "retrieval_mode": STATE["retrieval_mode"],
        "retrieved_case_ids": ", ".join(retrieved["case_id"].astype(str).tolist()),
        "prompt": prompt,
        "llm_raw_response": raw,
    }


def metrics_table(results: pd.DataFrame) -> pd.DataFrame:
    if results is None or results.empty or "correct" not in results.columns:
        return pd.DataFrame()
    rows = []
    for variant, group in results.groupby("variant", dropna=False):
        valid = group[group["correct"].isin([True, False])].copy()
        if valid.empty:
            continue
        actual = valid["actual_outcome"].map(normalize_label)
        pred = valid["llm_predicted_outcome"].map(normalize_label)
        labels = sorted(set(actual.dropna()) | set(pred.dropna()))
        positive = "1" if "1" in labels else labels[-1] if labels else ""
        tp = int(((actual == positive) & (pred == positive)).sum())
        fp = int(((actual != positive) & (pred == positive)).sum())
        tn = int(((actual != positive) & (pred != positive)).sum())
        fn = int(((actual == positive) & (pred != positive)).sum())
        accuracy = float((valid["correct"] == True).mean())
        precision = tp / (tp + fp) if tp + fp else 0.0
        recall = tp / (tp + fn) if tp + fn else 0.0
        f1 = 2 * precision * recall / (precision + recall) if precision + recall else 0.0
        rows.append(
            {
                "variant": variant,
                "variant_label": ABLATION_VARIANTS.get(variant, {}).get("label", variant),
                "n": len(valid),
                "accuracy": accuracy,
                "precision_positive": precision,
                "recall_positive": recall,
                "f1_positive": f1,
                "tp": tp,
                "fp": fp,
                "tn": tn,
                "fn": fn,
            }
        )
    return pd.DataFrame(rows)


def run_batch_job(row_indexes: List[Any], variants: List[str], neighbors: int) -> None:
    total = len(row_indexes) * len(variants)
    results = []
    set_batch_status(
        running=True,
        completed=0,
        total=total,
        current_row="",
        current_variant="",
        message="Starting MISQ ablation batch...",
        error="",
        finished=False,
        started_at=datetime.now().strftime("%H:%M:%S"),
    )
    try:
        completed = 0
        for row_index in row_indexes:
            for variant in variants:
                set_batch_status(
                    current_row=row_index,
                    current_variant=variant,
                    message=f"Processing row {row_index}, {ABLATION_VARIANTS[variant]['label']}...",
                )
                result = run_prediction_for_row(row_index, variant, neighbors)
                results.append(result)
                completed += 1
                result_df = pd.DataFrame(results)
                with STATE_LOCK:
                    STATE["batch_results"] = result_df
                    STATE["batch_metrics"] = metrics_table(result_df)
                set_batch_status(completed=completed, message=f"Completed {completed} of {total} predictions.")
        set_batch_status(
            running=False,
            completed=total,
            current_row="",
            current_variant="",
            message=f"Batch complete: {total} predictions generated.",
            error="",
            finished=True,
            finished_at=datetime.now().strftime("%H:%M:%S"),
        )
    except Exception as exc:
        set_batch_status(
            running=False,
            message="Batch stopped before completion.",
            error=str(exc),
            finished=True,
            finished_at=datetime.now().strftime("%H:%M:%S"),
        )


def css() -> str:
    return """
    <style>
      :root { --ink:#1f2933; --muted:#607080; --line:#d9e2ec; --panel:#f7f9fb; --accent:#4338ca; --accent-dark:#3730a3; }
      * { box-sizing:border-box; }
      body { margin:0; font-family:"Segoe UI", Arial, sans-serif; color:var(--ink); background:#fff; }
      header { padding:28px 40px 18px; border-bottom:1px solid var(--line); background:#fbfcfd; }
      main { padding:24px 40px 48px; max-width:1320px; }
      h1 { margin:0 0 8px; font-size:28px; font-weight:650; letter-spacing:0; }
      h2 { margin:0 0 16px; font-size:19px; font-weight:650; letter-spacing:0; }
      h3 { margin:18px 0 10px; font-size:16px; letter-spacing:0; }
      section { border-bottom:1px solid var(--line); padding:22px 0; }
      label { display:block; font-size:13px; font-weight:600; color:#344454; margin:0 0 6px; }
      input, select, textarea { width:100%; border:1px solid #b7c4d1; border-radius:6px; padding:9px 10px; font:inherit; background:#fff; }
      textarea { min-height:90px; resize:vertical; }
      button, .button { border:0; border-radius:6px; padding:10px 14px; background:var(--accent); color:#fff; font-weight:650; text-decoration:none; cursor:pointer; display:inline-block; }
      button:hover, .button:hover { background:var(--accent-dark); }
      button:disabled { background:#9aa2c8; cursor:wait; }
      .grid { display:grid; grid-template-columns:repeat(12, 1fr); gap:16px; align-items:end; }
      .span-2 { grid-column:span 2; } .span-3 { grid-column:span 3; } .span-4 { grid-column:span 4; } .span-5 { grid-column:span 5; } .span-6 { grid-column:span 6; } .span-8 { grid-column:span 8; } .span-12 { grid-column:span 12; }
      .muted { color:var(--muted); }
      .error { border-left:4px solid #b91c1c; padding:12px 14px; background:#fff5f5; color:#7f1d1d; }
      .metric { background:var(--panel); border:1px solid var(--line); border-radius:6px; padding:10px 12px; }
      .metrics { display:grid; grid-template-columns:repeat(auto-fit,minmax(170px,1fr)); gap:10px; margin-top:14px; }
      .data-wrap { overflow:auto; border:1px solid var(--line); border-radius:6px; }
      .data-table { width:100%; border-collapse:collapse; font-size:13px; }
      .data-table th, .data-table td { padding:8px 10px; border-bottom:1px solid var(--line); text-align:left; vertical-align:top; }
      .data-table th { background:var(--panel); position:sticky; top:0; z-index:1; }
      pre { white-space:pre-wrap; background:#f6f8fa; border:1px solid var(--line); border-radius:6px; padding:14px; max-height:420px; overflow:auto; }
      .actions { display:flex; gap:10px; flex-wrap:wrap; margin-top:12px; }
      .checklist label { font-weight:500; margin:8px 0; }
      .progress-panel { border:1px solid var(--line); border-radius:6px; background:#f7f9fb; padding:14px; margin-top:14px; }
      .progress-track { height:14px; background:#e6edf3; border-radius:999px; overflow:hidden; margin:10px 0 8px; }
      .progress-fill { height:100%; width:0%; background:var(--accent); transition:width .25s ease; }
      .progress-row { display:flex; justify-content:space-between; gap:12px; flex-wrap:wrap; font-size:13px; }
      .error-text { color:#b91c1c; }
      @media (max-width:820px) { header, main { padding-left:18px; padding-right:18px; } .grid { grid-template-columns:1fr; } .span-2,.span-3,.span-4,.span-5,.span-6,.span-8,.span-12 { grid-column:span 1; } }
    </style>
    """


def progress_script() -> str:
    return """
    <script>
      const panel = document.getElementById("batch-progress");
      async function refreshBatchStatus() {
        if (!panel) return;
        try {
          const response = await fetch("/batch-status", { cache: "no-store" });
          if (!response.ok) return;
          const status = await response.json();
          document.getElementById("batch-progress-fill").style.width = `${Math.max(0, Math.min(100, Number(status.percent || 0)))}%`;
          document.getElementById("batch-progress-label").textContent = status.message || "Waiting for batch status...";
          document.getElementById("batch-progress-count").textContent = `${status.completed || 0} of ${status.total || 0}`;
          document.getElementById("batch-progress-current").textContent =
            status.current_row ? `Current row: ${status.current_row}; variant: ${status.current_variant || ""}` : "";
          document.getElementById("batch-progress-error").textContent = status.error ? `Error: ${status.error}` : "";
          if (status.running) {
            window.setTimeout(refreshBatchStatus, 1200);
          } else if (status.finished && !window.batchCompletionReloaded) {
            window.batchCompletionReloaded = true;
            window.setTimeout(() => window.location.reload(), 1000);
          }
        } catch (_) {
          window.setTimeout(refreshBatchStatus, 2000);
        }
      }
      if (panel && panel.dataset.active === "true") refreshBatchStatus();
    </script>
    """


def page(body: str) -> bytes:
    status = ""
    if STATE.get("error"):
        status = f"<div class='error'><strong>Something needs attention.</strong><br>{esc(STATE['error'])}</div>"
    html_doc = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>MISQ E2R2 Ablation Tests</title>
  {css()}
</head>
<body>
  <header>
    <h1>MISQ E2R2 Ablation Tests</h1>
    <div class="muted">Run full E2R2 and ablated variants from exported case-base, SHAP, and holdout files.</div>
  </header>
  <main>{status}{body}</main>
  {progress_script()}
</body>
</html>"""
    return html_doc.encode("utf-8")


def upload_section() -> str:
    loaded = STATE["holdout"] is not None
    metrics = ""
    if loaded:
        warning = (
            f"<div class='warn'>{esc(STATE.get('shap_convention_warning', ''))}</div>"
            if STATE.get("shap_convention_warning")
            else ""
        )
        metrics = f"""
        <div class="metrics">
          <div class="metric"><strong>{len(STATE['case_base'])}</strong><br><span class="muted">case-base records</span></div>
          <div class="metric"><strong>{len(STATE['shap_scores'])}</strong><br><span class="muted">SHAP rows</span></div>
          <div class="metric"><strong>{len(STATE['holdout'])}</strong><br><span class="muted">holdout rows</span></div>
          <div class="metric"><strong>{esc(STATE['target_column'])}</strong><br><span class="muted">actual outcome column</span></div>
          <div class="metric"><strong>{esc(STATE['retrieval_mode'])}</strong><br><span class="muted">retrieval mode</span></div>
        </div>
        {warning}
        """
    return f"""
    <section>
      <h2>Experiment Files</h2>
      <form method="post" action="/upload" enctype="multipart/form-data">
        <div class="grid">
          <div class="span-4"><label>Case base CSV</label><input name="case_base" type="file" accept=".csv,.xlsx,.xls" required></div>
          <div class="span-4"><label>SHAP scores CSV</label><input name="shap_scores" type="file" accept=".csv,.xlsx,.xls" required></div>
          <div class="span-4"><label>Holdout dataset CSV</label><input name="holdout" type="file" accept=".csv,.xlsx,.xls" required></div>
          <div class="span-4"><label>Case vectors CSV</label><input name="case_vectors" type="file" accept=".csv,.xlsx,.xls"></div>
          <div class="span-4"><label>Holdout vectors CSV</label><input name="holdout_vectors" type="file" accept=".csv,.xlsx,.xls"></div>
          <div class="span-4"><label>Holdout SHAP CSV</label><input name="holdout_shap" type="file" accept=".csv,.xlsx,.xls"></div>
          <div class="span-12"><button type="submit">Load experiment files</button></div>
        </div>
      </form>
      <p class="muted">Holdout SHAP is optional. If omitted, the attribution-only ablation uses retrieved-case SHAP summaries as a proxy.</p>
      {metrics}
    </section>
    """


def settings_section() -> str:
    if STATE["holdout"] is None:
        return ""
    saved = "Saved" if STATE.get("api_key") else "Not saved"
    variant_checks = []
    selected = set(STATE.get("variants") or [])
    for value, meta in ABLATION_VARIANTS.items():
        checked = " checked" if value in selected else ""
        variant_checks.append(
            f"<label><input style='width:auto' name='variants' type='checkbox' value='{esc(value)}'{checked}> "
            f"{esc(meta['label'])}<br><span class='muted'>{esc(meta['description'])}</span></label>"
        )
    return f"""
    <section>
      <h2>LLM and Test Settings</h2>
      <form method="post" action="/settings">
        <div class="grid">
          <div class="span-5"><label>OpenAI API key</label><input name="api_key" type="password" autocomplete="off" placeholder="Paste once; stored in this local app session"></div>
          <div class="span-3"><label>API key status</label><input value="{saved}" disabled></div>
          <div class="span-4"><label>LLM model</label><select name="model">{model_option_tags(STATE['model'])}</select></div>
          <div class="span-12"><p class="muted">Full E2R2 prompts use precedent-based reasoning first, then a separate baseline-model verification step using the exported baseline prediction and confidence.</p></div>
          <div class="span-12"><label>Prediction goal</label><textarea name="prediction_goal">{esc(STATE.get('prediction_goal', ''))}</textarea></div>
          <div class="span-12 checklist"><label>Ablation variants</label>{''.join(variant_checks)}</div>
          <div class="span-12"><button type="submit">Save settings</button></div>
        </div>
      </form>
    </section>
    """


def individual_section() -> str:
    if STATE["holdout"] is None:
        return ""
    holdout = STATE["holdout"]
    options = "\n".join(
        f"<option value='{esc(value)}'>Row {esc(value)}</option>"
        for value in holdout["row_index"].head(1000).tolist()
    )
    variant_options = "\n".join(
        f"<option value='{esc(value)}'>{esc(meta['label'])}</option>"
        for value, meta in ABLATION_VARIANTS.items()
    )
    result = STATE.get("individual_result")
    result_html = ""
    if result:
        compact = pd.DataFrame([{k: v for k, v in result.items() if k not in {"prompt", "llm_raw_response"}}])
        result_html = f"""
        <h3>Latest Individual Result</h3>
        <div class="data-wrap">{table_html(compact, max_rows=1)}</div>
        <h3>Prompt</h3><pre>{esc(result.get('prompt'))}</pre>
        <h3>Raw LLM Response</h3><pre>{esc(result.get('llm_raw_response'))}</pre>
        """
    return f"""
    <section>
      <h2>Individual Test</h2>
      <form method="post" action="/predict-one">
        <div class="grid">
          <div class="span-4"><label>Holdout row</label><select name="row_index">{options}</select></div>
          <div class="span-4"><label>Variant</label><select name="variant">{variant_options}</select></div>
          <div class="span-2"><label>Retrieved cases</label><input name="neighbors" type="number" min="1" max="25" value="5"></div>
          <div class="span-12"><button type="submit">Generate test prediction</button></div>
        </div>
      </form>
      {result_html}
    </section>
    """


def batch_section() -> str:
    if STATE["holdout"] is None:
        return ""
    status = get_batch_status()
    running = bool(status.get("running"))
    progress_html = ""
    if running or status.get("total"):
        progress_html = f"""
        <div id="batch-progress" class="progress-panel" data-active="{'true' if running else 'false'}">
          <div class="progress-row">
            <strong id="batch-progress-label">{esc(status.get('message', ''))}</strong>
            <span id="batch-progress-count">{esc(status.get('completed', 0))} of {esc(status.get('total', 0))}</span>
          </div>
          <div class="progress-track"><div id="batch-progress-fill" class="progress-fill" style="width:{esc(status.get('percent', 0))}%"></div></div>
          <div class="progress-row">
            <span id="batch-progress-current" class="muted">{esc(status.get('current_row', ''))}</span>
            <span id="batch-progress-error" class="error-text">{'Error: ' + esc(status.get('error')) if status.get('error') else ''}</span>
          </div>
        </div>
        """
    results = STATE.get("batch_results")
    metrics = STATE.get("batch_metrics")
    result_html = ""
    if metrics is not None and not metrics.empty:
        result_html += f"""
        <h3>Metrics</h3>
        <div class="actions">
          <a class="button" href="/download?name=metrics">Download metrics</a>
          <a class="button" href="/download?name=batch">Download predictions</a>
        </div>
        <div class="data-wrap">{table_html(metrics, max_rows=20)}</div>
        """
    if results is not None and not results.empty:
        result_html += f"""
        <h3>Prediction Results</h3>
        <div class="data-wrap">{table_html(results.drop(columns=['prompt', 'llm_raw_response'], errors='ignore'), max_rows=25)}</div>
        """
    return f"""
    <section>
      <h2>Batch Ablation Tests</h2>
      <form method="post" action="/predict-batch">
        <div class="grid">
          <div class="span-3"><label>Start after first rows</label><input name="offset" type="number" min="0" value="0"></div>
          <div class="span-3"><label>Number of rows</label><input name="limit" type="number" min="1" value="25"></div>
          <div class="span-2"><label>Retrieved cases</label><input name="neighbors" type="number" min="1" max="25" value="5"></div>
          <div class="span-12"><button type="submit"{' disabled' if running else ''}>{'Batch is running' if running else 'Run selected variants'}</button></div>
        </div>
      </form>
      <p class="muted">The batch runs every selected variant for each selected holdout row. Large batches can use substantial API credits.</p>
      {progress_html}
      {result_html}
    </section>
    """


def home() -> bytes:
    body = upload_section() + settings_section() + individual_section() + batch_section()
    return page(body)


class MISQTestsHandler(BaseHTTPRequestHandler):
    def do_GET(self) -> None:
        parsed = urlparse(self.path)
        if parsed.path == "/download":
            self.handle_download(parse_qs(parsed.query))
            return
        if parsed.path == "/batch-status":
            self.respond_json(get_batch_status())
            return
        self.respond(200, home())

    def do_POST(self) -> None:
        try:
            STATE["error"] = None
            parsed = urlparse(self.path)
            if parsed.path == "/upload":
                self.handle_upload()
            elif parsed.path == "/settings":
                self.handle_settings()
            elif parsed.path == "/predict-one":
                self.handle_predict_one()
            elif parsed.path == "/predict-batch":
                self.handle_predict_batch()
            else:
                self.respond(404, page("<section><h2>Not found</h2></section>"))
        except Exception as exc:
            STATE["error"] = f"{exc}\n\n{traceback.format_exc(limit=3)}"
            self.respond(500, home())

    def handle_upload(self) -> None:
        form = parse_post(self)
        case_base = load_upload(form["case_base"]) if "case_base" in form else None
        shap_scores = load_upload(form["shap_scores"]) if "shap_scores" in form else None
        holdout = load_upload(form["holdout"]) if "holdout" in form else None
        case_vectors = load_upload(form["case_vectors"]) if "case_vectors" in form else None
        holdout_vectors = load_upload(form["holdout_vectors"]) if "holdout_vectors" in form else None
        holdout_shap = load_upload(form["holdout_shap"]) if "holdout_shap" in form else None
        if case_base is None or shap_scores is None or holdout is None:
            raise ValueError("Upload case base, SHAP scores, and holdout dataset.")
        prepare_loaded_data(case_base, shap_scores, holdout, case_vectors, holdout_vectors, holdout_shap)
        self.redirect("/")

    def handle_settings(self) -> None:
        form = parse_post(self)
        api_key = form_get(form, "api_key", "")
        if api_key:
            STATE["api_key"] = api_key
        STATE["model"] = form_get(form, "model", STATE["model"])
        STATE["prediction_goal"] = form_get(form, "prediction_goal", "")
        STATE["include_baseline_signal"] = False
        variants = form_get(form, "variants", STATE["variants"])
        if isinstance(variants, str):
            variants = [variants]
        STATE["variants"] = [v for v in variants if v in ABLATION_VARIANTS] or ["full_e2r2"]
        self.redirect("/")

    def handle_predict_one(self) -> None:
        form = parse_post(self)
        row_index = form_get(form, "row_index")
        row_index = int(row_index) if str(row_index).isdigit() else row_index
        variant = form_get(form, "variant", "full_e2r2")
        neighbors = int(float(form_get(form, "neighbors", 5)))
        STATE["individual_result"] = run_prediction_for_row(row_index, variant, neighbors)
        self.redirect("/")

    def handle_predict_batch(self) -> None:
        form = parse_post(self)
        if get_batch_status().get("running"):
            raise ValueError("A batch is already running. Wait for it to finish before starting another.")
        if not STATE.get("api_key"):
            raise ValueError("Enter and save your OpenAI API key first.")
        offset = int(float(form_get(form, "offset", 0)))
        limit = int(float(form_get(form, "limit", 25)))
        neighbors = int(float(form_get(form, "neighbors", 5)))
        row_indexes = STATE["holdout"]["row_index"].iloc[offset : offset + limit].tolist()
        if not row_indexes:
            raise ValueError("No holdout rows were selected for this batch.")
        variants = [v for v in STATE.get("variants", []) if v in ABLATION_VARIANTS]
        if not variants:
            raise ValueError("Select at least one ablation variant.")
        with STATE_LOCK:
            STATE["batch_results"] = None
            STATE["batch_metrics"] = None
        set_batch_status(
            running=True,
            completed=0,
            total=len(row_indexes) * len(variants),
            message="Starting MISQ ablation batch...",
            error="",
            finished=False,
        )
        thread = threading.Thread(target=run_batch_job, args=(row_indexes, variants, neighbors), daemon=True)
        thread.start()
        self.redirect("/")

    def handle_download(self, query: Dict[str, Any]) -> None:
        name = query.get("name", [""])[0]
        if name == "batch":
            df = STATE.get("batch_results")
            filename = "misq_ablation_predictions.csv"
        elif name == "metrics":
            df = STATE.get("batch_metrics")
            filename = "misq_ablation_metrics.csv"
        else:
            self.respond(404, page("<section><h2>Download not found.</h2></section>"))
            return
        if df is None or df.empty:
            self.respond(404, page("<section><h2>No results to download.</h2></section>"))
            return
        payload = dataframe_to_csv_bytes(df)
        self.send_response(200)
        self.send_header("Content-Type", "text/csv; charset=utf-8")
        self.send_header("Content-Disposition", f'attachment; filename="{filename}"')
        self.send_header("Content-Length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)

    def redirect(self, location: str) -> None:
        self.send_response(303)
        self.send_header("Location", location)
        self.end_headers()

    def respond(self, status: int, payload: bytes) -> None:
        self.send_response(status)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)

    def respond_json(self, payload: Dict[str, Any]) -> None:
        body = json.dumps(payload, default=str).encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, format: str, *args: Any) -> None:
        return


def run() -> None:
    server = None
    port = DEFAULT_PORT
    for candidate in range(DEFAULT_PORT, DEFAULT_PORT + 30):
        try:
            server = ThreadingHTTPServer((HOST, candidate), MISQTestsHandler)
            port = candidate
            break
        except OSError:
            continue
    if server is None:
        raise RuntimeError("No open local port was found for the MISQ tests app.")
    url = f"http://{HOST}:{port}"
    print(f"MISQ E2R2 Ablation Tests running at {url}")
    threading.Timer(0.8, lambda: webbrowser.open(url)).start()
    server.serve_forever()


if __name__ == "__main__":
    run()
